package net.fivew14.authlogic.server.state;

import net.fivew14.authlogic.crypto.EncryptionProvider;
import net.fivew14.authlogic.crypto.KeysProvider;
import net.fivew14.authlogic.crypto.OptionalKeyPair;

import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.UUID;

public abstract class CommonAuthState {
    public String username;
    public UUID playerUUID;

    public long serverNonce; // Nonce that is generated by the server.

    /**
     * Timestamp when this auth state was created, in milliseconds since epoch.
     * Used for cleanup of stale states.
     */
    public final long createdAt = System.currentTimeMillis();
    public long clientNonce; // Nonce that is generated by the client.

    public OptionalKeyPair serverTemporaryKeys = new OptionalKeyPair();
    public OptionalKeyPair clientTemporaryKeys = new OptionalKeyPair();

    public PublicKey clientConstPublicKey;
    public PublicKey serverConstPublicKey;

    private byte[] getSharedKey() {
        PrivateKey privateKey;
        PublicKey publicKey;

        if (serverTemporaryKeys.hasPrivateKey()) {
            privateKey = serverTemporaryKeys.privateKey;
            publicKey = clientTemporaryKeys.publicKey;
        } else {
            privateKey = clientTemporaryKeys.privateKey;
            publicKey = serverTemporaryKeys.publicKey;
        }

        return KeysProvider.generateSharedSecret(privateKey, publicKey).getEncoded();
    }

    public byte[] encryptBlob(byte[] blob) {
        return EncryptionProvider.encrypt(getSharedKey(), blob);
    }

    public byte[] decryptBlob(byte[] blob) {
        return EncryptionProvider.decrypt(getSharedKey(), blob);
    }

    public abstract boolean isAuthenticated();

    public abstract boolean isFinished();
}
